In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv(r'../data\raw\spy_2020_2022.csv', low_memory = False)

In [3]:
df.shape

(3589079, 33)

In [4]:
df.sample(5).T

,832091,574824,2431310,3433595,1284267
[QUOTE_UNIXTIME],1657656000,1597953600,1648152000,1615582800,1606942800
[QUOTE_READTIME],2022-07-12 16:00,2020-08-20 16:00,2022-03-24 16:00,2021-03-12 16:00,2020-12-02 16:00
[QUOTE_DATE],2022-07-12,2020-08-20,2022-03-24,2021-03-12,2020-12-02
[QUOTE_TIME_HOURS],16.0,16.0,16.0,16.0,16.0
[UNDERLYING_LAST],380.87,338.31,450.42,394.02,366.82
[EXPIRE_DATE],2022-08-01,2020-09-04,2024-01-19,2021-04-16,2020-12-14
[EXPIRE_UNIX],1659384000,1599249600,1705698000,1618603200,1607979600
[DTE],20.0,15.0,666.04,34.96,12.0
[C_DELTA],0.004250,0.245130,0.305150,1.000000,0.172180
[C_GAMMA],0.000580,0.032940,0.003240,0.000000,0.026990
[C_VEGA],0.010650,0.222630,2.133140,0.000000,0.176530
[C_THETA],-0.005520,-0.092840,-0.028650,0.000000,-0.092890
[C_RHO],0.001100,0.035300,2.175200,0.000000,0.022260
[C_IV],0.224330,0.134920,0.175030,,0.136210
[C_VOLUME],0.000000,,81.000000,,15.000000
[C_LAST],0.030000,1.360000,19.200000,0.000000,0.840000
[C_SIZE],602 x 7662,80 x 80,21 x 1,104 x 125,1695 x 1504
[C_BID],0.020000,1.360000,17.000000,223.490000,0.850000
[C_ASK],0.030000,1.370000,20.000000,224.390000,0.860000
[STRIKE],440.0,345.0,525.0,170.0,376.0
[P_BID],58.900000,7.930000,83.500000,0.010000,10.090000
[P_ASK],59.710000,7.960000,88.500000,0.020000,10.170000
[P_SIZE],50 x 90,23 x 1,10 x 10,4706 x 1713,25 x 50
[P_LAST],0.000000,7.980000,97.850000,0.020000,10.250000
[P_DELTA],-0.937750,-0.771830,-0.737840,-0.000660,-0.816670
[P_GAMMA],0.001820,0.034120,0.003550,0.000000,0.026360
[P_VEGA],0.098620,0.213710,1.969040,0.002730,0.184070
[P_THETA],-0.077640,-0.087730,-0.020170,-0.002330,-0.100460
[P_RHO],-0.066630,-0.117890,-5.560050,-0.000140,-0.092690
[P_IV],0.359690,0.124940,0.151710,0.847210,0.142010
[P_VOLUME],,17.000000,0.000000,101.000000,0.000000
[STRIKE_DISTANCE],59.1,6.7,74.6,224.0,9.2
[STRIKE_DISTANCE_PCT],0.155,0.02,0.166,0.569,0.025

In [5]:
df.columns = df.columns.str.strip('[ ]').str.lower()
df.columns

Index(['quote_unixtime', 'quote_readtime', 'quote_date', 'quote_time_hours',
       'underlying_last', 'expire_date', 'expire_unix', 'dte', 'c_delta',
       'c_gamma', 'c_vega', 'c_theta', 'c_rho', 'c_iv', 'c_volume', 'c_last',
       'c_size', 'c_bid', 'c_ask', 'strike', 'p_bid', 'p_ask', 'p_size',
       'p_last', 'p_delta', 'p_gamma', 'p_vega', 'p_theta', 'p_rho', 'p_iv',
       'p_volume', 'strike_distance', 'strike_distance_pct'],
      dtype='str')

In [ ]:
c_parts = df['c_size'].str.split('x', expand = True)
df['c_size_bid'] = c_parts[0]
df['c_size_ask'] = c_parts[1]

In [ ]:
p_parts = df['p_size'].str.split('x', expand = True)
df['p_size_bid'] = p_parts[0]
df['p_size_ask'] = p_parts[1]

In [8]:
df[['c_size_bid', 'c_size_ask', 'c_size']].sample(5)

        c_size_bid c_size_ask      c_size
2820624         0        3093    0 x 3093
2583753        89          50     89 x 50
1393417        10          24     10 x 24
561561         17          17     17 x 17
2897238       252         252   252 x 252

In [9]:
df[['p_size_bid', 'p_size_ask', 'p_size']].sample(5)

        p_size_bid p_size_ask        p_size
2463321      2978        9436   2978 x 9436
1003134        50          10       50 x 10
734003        262         272     262 x 272
1563238        19           1        19 x 1
2678479         5           5         5 x 5

In [10]:
df = df.drop(columns = ['c_size', 'p_size'])

In [11]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3589079 entries, 0 to 3589078
Data columns (total 35 columns):
 #   Column               Dtype
---  ------               -----
 0   quote_unixtime       int64
 1   quote_readtime       str
 2   quote_date           str
 3   quote_time_hours     float64
 4   underlying_last      float64
 5   expire_date          str
 6   expire_unix          int64
 7   dte                  float64
 8   c_delta              str
 9   c_gamma              str
 10  c_vega               str
 11  c_theta              str
 12  c_rho                str
 13  c_iv                 str
 14  c_volume             str
 15  c_last               str
 16  c_bid                str
 17  c_ask                str
 18  strike               float64
 19  p_bid                str
 20  p_ask                str
 21  p_last               str
 22  p_delta              str
 23  p_gamma              str
 24  p_vega               str
 25  p_theta              str
 26  p_rho                str
 27  p_iv                 str
 28  p_volume             str
 29  strike_distance      float64
 30  strike_distance_pct  float64
 31  c_size_bid           str
 32  c_size_ask           str
 33  p_size_bid           str
 34  p_size_ask           str
dtypes: float64(6), int64(2), str(27)
memory usage: 1.7 GB

In [12]:
to_num = ['c_delta',
       'c_gamma', 'c_vega', 'c_theta', 'c_rho', 'c_iv', 'c_volume', 'c_last',
       'c_size_bid', 'c_size_ask', 'c_bid', 'c_ask', 'strike', 'p_bid', 'p_ask', 'p_size_bid','p_size_ask',
       'p_last', 'p_delta', 'p_gamma', 'p_vega', 'p_theta', 'p_rho', 'p_iv',
       'p_volume', 'strike_distance', 'strike_distance_pct']

In [13]:
for i in to_num :
    df[i] = pd.to_numeric(df[i], errors = 'coerce')

In [14]:
df.columns

Index(['quote_unixtime', 'quote_readtime', 'quote_date', 'quote_time_hours',
       'underlying_last', 'expire_date', 'expire_unix', 'dte', 'c_delta',
       'c_gamma', 'c_vega', 'c_theta', 'c_rho', 'c_iv', 'c_volume', 'c_last',
       'c_bid', 'c_ask', 'strike', 'p_bid', 'p_ask', 'p_last', 'p_delta',
       'p_gamma', 'p_vega', 'p_theta', 'p_rho', 'p_iv', 'p_volume',
       'strike_distance', 'strike_distance_pct', 'c_size_bid', 'c_size_ask',
       'p_size_bid', 'p_size_ask'],
      dtype='str')

In [15]:
df[['quote_unixtime', 'quote_readtime', 'quote_date', 'quote_time_hours',
       'underlying_last', 'expire_date', 'expire_unix', 'dte']].head()

,quote_unixtime,quote_readtime,quote_date,quote_time_hours,underlying_last,expire_date,expire_unix,dte
0,1630526400,2021-09-01 16:00,2021-09-01,16.0,451.85,2021-09-01,1630526400,0.0
1,1630526400,2021-09-01 16:00,2021-09-01,16.0,451.85,2021-09-01,1630526400,0.0
2,1630526400,2021-09-01 16:00,2021-09-01,16.0,451.85,2021-09-01,1630526400,0.0
3,1630526400,2021-09-01 16:00,2021-09-01,16.0,451.85,2021-09-01,1630526400,0.0
4,1630526400,2021-09-01 16:00,2021-09-01,16.0,451.85,2021-09-01,1630526400,0.0

In [16]:
to_time = ['quote_readtime', 'quote_date', 'expire_date']

In [17]:
for i in to_time :
    df[i] = pd.to_datetime(df[i])

In [18]:
df[to_time].info()

<class 'pandas.DataFrame'>
RangeIndex: 3589079 entries, 0 to 3589078
Data columns (total 3 columns):
 #   Column          Dtype
---  ------          -----
 0   quote_readtime  datetime64[us]
 1   quote_date      datetime64[us]
 2   expire_date     datetime64[us]
dtypes: datetime64[us](3)
memory usage: 82.1 MB

In [19]:
df[['quote_unixtime', 'quote_readtime', 'quote_date', 'quote_time_hours',
       'underlying_last', 'expire_date', 'expire_unix', 'dte']].head()

,quote_unixtime,quote_readtime,quote_date,quote_time_hours,underlying_last,expire_date,expire_unix,dte
0,1630526400,2021-09-01 16:00:00,2021-09-01,16.0,451.85,2021-09-01,1630526400,0.0
1,1630526400,2021-09-01 16:00:00,2021-09-01,16.0,451.85,2021-09-01,1630526400,0.0
2,1630526400,2021-09-01 16:00:00,2021-09-01,16.0,451.85,2021-09-01,1630526400,0.0
3,1630526400,2021-09-01 16:00:00,2021-09-01,16.0,451.85,2021-09-01,1630526400,0.0
4,1630526400,2021-09-01 16:00:00,2021-09-01,16.0,451.85,2021-09-01,1630526400,0.0

In [21]:
holidays = ['2022-01-17',
'2022-02-21',
'2022-04-15',
'2022-05-30',
'2022-06-20',
'2022-07-04',
'2022-09-05',
'2022-11-24',
'2022-12-26']

In [22]:
holidays = pd.to_datetime(holidays)

In [23]:
df.columns

Index(['quote_unixtime', 'quote_readtime', 'quote_date', 'quote_time_hours',
       'underlying_last', 'expire_date', 'expire_unix', 'dte', 'c_delta',
       'c_gamma', 'c_vega', 'c_theta', 'c_rho', 'c_iv', 'c_volume', 'c_last',
       'c_bid', 'c_ask', 'strike', 'p_bid', 'p_ask', 'p_last', 'p_delta',
       'p_gamma', 'p_vega', 'p_theta', 'p_rho', 'p_iv', 'p_volume',
       'strike_distance', 'strike_distance_pct', 'c_size_bid', 'c_size_ask',
       'p_size_bid', 'p_size_ask'],
      dtype='str')

In [24]:
df.shape

(3589079, 35)

In [25]:
df = df[~df['quote_date'].isin(holidays)]

In [26]:
df.shape

(3549809, 35)

In [27]:
df.to_parquet(r'../data\processed\raw.parquet')