In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv(r'../data\raw\spy_2020_2022.csv', low_memory = False)

In [3]:
df.shape

(3589079, 33)

In [4]:
df.sample(5).T

,397140,2671327,2477976,3286329,1959787
[QUOTE_UNIXTIME],1663963200,1623182400,1578690000,1619640000,1583269200
[QUOTE_READTIME],2022-09-23 16:00,2021-06-08 16:00,2020-01-10 16:00,2021-04-28 16:00,2020-03-03 16:00
[QUOTE_DATE],2022-09-23,2021-06-08,2020-01-10,2021-04-28,2020-03-03
[QUOTE_TIME_HOURS],16.0,16.0,16.0,16.0,16.0
[UNDERLYING_LAST],367.93,422.27,325.64,417.39,300.32
[EXPIRE_DATE],2023-12-15,2021-06-25,2020-01-17,2021-12-17,2020-04-17
[EXPIRE_UNIX],1702674000,1624651200,1579294800,1639774800,1587153600
[DTE],448.04,17.0,7.0,233.04,44.96
[C_DELTA],0.697940,0.891180,0.627050,0.748050,0.000800
[C_GAMMA],0.003150,0.000100,0.075440,0.004160,0.000060
[C_VEGA],1.414760,0.106300,0.182770,1.052110,0.003180
[C_THETA],-0.057470,-0.054940,-0.116610,-0.047220,-0.001160
[C_RHO],2.367130,0.012510,0.041260,1.322820,0.000550
[C_IV],0.272790,2.106680,0.105030,0.235190,0.347240
[C_VOLUME],0.000000,,,1.000000,0.000000
[C_LAST],69.860000,0.000000,2.880000,48.080000,0.010000
[C_SIZE],162 x 208,10 x 10,60 x 20,5 x 1,0 x 1967
[C_BID],62.050000,202.060000,2.890000,54.400000,0.000000
[C_ASK],66.270000,202.590000,2.910000,56.470000,0.020000
[STRIKE],340.0,220.0,324.0,373.0,440.0
[P_BID],24.190000,0.000000,1.050000,12.570000,140.210000
[P_ASK],25.620000,0.010000,1.060000,12.820000,141.650000
[P_SIZE],109 x 71,0 x 2950,169 x 301,84 x 84,20 x 22
[P_LAST],25.870000,0.020000,1.030000,12.710000,0.000000
[P_DELTA],-0.307830,0.000000,-0.355330,-0.250530,-0.993960
[P_GAMMA],0.003320,0.000010,0.085900,0.004090,0.000000
[P_VEGA],1.426230,0.000910,0.179440,1.058920,0.000000
[P_THETA],-0.034140,-0.001610,-0.107070,-0.054680,-0.037190
[P_RHO],-1.425050,-0.000010,-0.025420,-0.750580,-0.554390
[P_IV],0.269090,0.860440,0.089610,0.230970,0.000710
[P_VOLUME],8.000000,5.000000,,0.000000,
[STRIKE_DISTANCE],27.9,202.3,1.6,44.4,139.7
[STRIKE_DISTANCE_PCT],0.076,0.479,0.005,0.106,0.465

In [5]:
df.columns = df.columns.str.strip('[ ]').str.lower()
df.columns

Index(['quote_unixtime', 'quote_readtime', 'quote_date', 'quote_time_hours',
       'underlying_last', 'expire_date', 'expire_unix', 'dte', 'c_delta',
       'c_gamma', 'c_vega', 'c_theta', 'c_rho', 'c_iv', 'c_volume', 'c_last',
       'c_size', 'c_bid', 'c_ask', 'strike', 'p_bid', 'p_ask', 'p_size',
       'p_last', 'p_delta', 'p_gamma', 'p_vega', 'p_theta', 'p_rho', 'p_iv',
       'p_volume', 'strike_distance', 'strike_distance_pct'],
      dtype='str')

In [6]:
c_parts = df['c_size'].str.split('x', expand = True)
df['c_size_bid'] = c_parts[0]
df['c_size_ask'] = c_parts[1]

In [7]:
p_parts = df['p_size'].str.split('x', expand = True)
df['p_size_bid'] = p_parts[0]
df['p_size_ask'] = p_parts[1]

In [8]:
df[['c_size_bid', 'c_size_ask', 'c_size']].sample(5)

        c_size_bid c_size_ask      c_size
2592918         1           1       1 x 1
2688268       286         165   286 x 165
1757409       422         374   422 x 374
3577332       328           3     328 x 3
2097384       322         204   322 x 204

In [9]:
df[['p_size_bid', 'p_size_ask', 'p_size']].sample(5)

        p_size_bid p_size_ask        p_size
3357215      1128        1880   1128 x 1880
2048138        10          10       10 x 10
1407336        10           3        10 x 3
2681708      1313        1118   1313 x 1118
2149926         1           1         1 x 1

In [10]:
df = df.drop(columns = ['c_size', 'p_size'])

In [11]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3589079 entries, 0 to 3589078
Data columns (total 35 columns):
 #   Column               Dtype
---  ------               -----
 0   quote_unixtime       int64
 1   quote_readtime       str
 2   quote_date           str
 3   quote_time_hours     float64
 4   underlying_last      float64
 5   expire_date          str
 6   expire_unix          int64
 7   dte                  float64
 8   c_delta              str
 9   c_gamma              str
 10  c_vega               str
 11  c_theta              str
 12  c_rho                str
 13  c_iv                 str
 14  c_volume             str
 15  c_last               str
 16  c_bid                str
 17  c_ask                str
 18  strike               float64
 19  p_bid                str
 20  p_ask                str
 21  p_last               str
 22  p_delta              str
 23  p_gamma              str
 24  p_vega               str
 25  p_theta              str
 26  p_rho                str
 27  p_iv                 str
 28  p_volume             str
 29  strike_distance      float64
 30  strike_distance_pct  float64
 31  c_size_bid           str
 32  c_size_ask           str
 33  p_size_bid           str
 34  p_size_ask           str
dtypes: float64(6), int64(2), str(27)
memory usage: 1.7 GB

In [12]:
to_num = ['c_delta',
       'c_gamma', 'c_vega', 'c_theta', 'c_rho', 'c_iv', 'c_volume', 'c_last',
       'c_size_bid', 'c_size_ask', 'c_bid', 'c_ask', 'strike', 'p_bid', 'p_ask', 'p_size_bid','p_size_ask',
       'p_last', 'p_delta', 'p_gamma', 'p_vega', 'p_theta', 'p_rho', 'p_iv',
       'p_volume', 'strike_distance', 'strike_distance_pct']

In [13]:
for i in to_num :
    df[i] = pd.to_numeric(df[i], errors = 'coerce')

In [14]:
df.columns

Index(['quote_unixtime', 'quote_readtime', 'quote_date', 'quote_time_hours',
       'underlying_last', 'expire_date', 'expire_unix', 'dte', 'c_delta',
       'c_gamma', 'c_vega', 'c_theta', 'c_rho', 'c_iv', 'c_volume', 'c_last',
       'c_bid', 'c_ask', 'strike', 'p_bid', 'p_ask', 'p_last', 'p_delta',
       'p_gamma', 'p_vega', 'p_theta', 'p_rho', 'p_iv', 'p_volume',
       'strike_distance', 'strike_distance_pct', 'c_size_bid', 'c_size_ask',
       'p_size_bid', 'p_size_ask'],
      dtype='str')

In [15]:
df[['quote_unixtime', 'quote_readtime', 'quote_date', 'quote_time_hours',
       'underlying_last', 'expire_date', 'expire_unix', 'dte']].head()

,quote_unixtime,quote_readtime,quote_date,quote_time_hours,underlying_last,expire_date,expire_unix,dte
0,1630526400,2021-09-01 16:00,2021-09-01,16.0,451.85,2021-09-01,1630526400,0.0
1,1630526400,2021-09-01 16:00,2021-09-01,16.0,451.85,2021-09-01,1630526400,0.0
2,1630526400,2021-09-01 16:00,2021-09-01,16.0,451.85,2021-09-01,1630526400,0.0
3,1630526400,2021-09-01 16:00,2021-09-01,16.0,451.85,2021-09-01,1630526400,0.0
4,1630526400,2021-09-01 16:00,2021-09-01,16.0,451.85,2021-09-01,1630526400,0.0

In [16]:
to_time = ['quote_readtime', 'quote_date', 'expire_date']

In [17]:
for i in to_time :
    df[i] = pd.to_datetime(df[i])

In [18]:
df[to_time].info()

<class 'pandas.DataFrame'>
RangeIndex: 3589079 entries, 0 to 3589078
Data columns (total 3 columns):
 #   Column          Dtype
---  ------          -----
 0   quote_readtime  datetime64[us]
 1   quote_date      datetime64[us]
 2   expire_date     datetime64[us]
dtypes: datetime64[us](3)
memory usage: 82.1 MB

In [19]:
df[['quote_unixtime', 'quote_readtime', 'quote_date', 'quote_time_hours',
       'underlying_last', 'expire_date', 'expire_unix', 'dte']].head()

,quote_unixtime,quote_readtime,quote_date,quote_time_hours,underlying_last,expire_date,expire_unix,dte
0,1630526400,2021-09-01 16:00:00,2021-09-01,16.0,451.85,2021-09-01,1630526400,0.0
1,1630526400,2021-09-01 16:00:00,2021-09-01,16.0,451.85,2021-09-01,1630526400,0.0
2,1630526400,2021-09-01 16:00:00,2021-09-01,16.0,451.85,2021-09-01,1630526400,0.0
3,1630526400,2021-09-01 16:00:00,2021-09-01,16.0,451.85,2021-09-01,1630526400,0.0
4,1630526400,2021-09-01 16:00:00,2021-09-01,16.0,451.85,2021-09-01,1630526400,0.0

In [20]:
holidays = ['2022-01-17',
'2022-02-21',
'2022-04-15',
'2022-05-30',
'2022-06-20',
'2022-07-04',
'2022-09-05',
'2022-11-24',
'2022-12-26']

In [21]:
holidays = pd.to_datetime(holidays)

In [22]:
df.columns

Index(['quote_unixtime', 'quote_readtime', 'quote_date', 'quote_time_hours',
       'underlying_last', 'expire_date', 'expire_unix', 'dte', 'c_delta',
       'c_gamma', 'c_vega', 'c_theta', 'c_rho', 'c_iv', 'c_volume', 'c_last',
       'c_bid', 'c_ask', 'strike', 'p_bid', 'p_ask', 'p_last', 'p_delta',
       'p_gamma', 'p_vega', 'p_theta', 'p_rho', 'p_iv', 'p_volume',
       'strike_distance', 'strike_distance_pct', 'c_size_bid', 'c_size_ask',
       'p_size_bid', 'p_size_ask'],
      dtype='str')

In [23]:
df.shape

(3589079, 35)

In [24]:
df = df[~df['quote_date'].isin(holidays)]

In [25]:
df.shape

(3549809, 35)

In [26]:
df.columns

Index(['quote_unixtime', 'quote_readtime', 'quote_date', 'quote_time_hours',
       'underlying_last', 'expire_date', 'expire_unix', 'dte', 'c_delta',
       'c_gamma', 'c_vega', 'c_theta', 'c_rho', 'c_iv', 'c_volume', 'c_last',
       'c_bid', 'c_ask', 'strike', 'p_bid', 'p_ask', 'p_last', 'p_delta',
       'p_gamma', 'p_vega', 'p_theta', 'p_rho', 'p_iv', 'p_volume',
       'strike_distance', 'strike_distance_pct', 'c_size_bid', 'c_size_ask',
       'p_size_bid', 'p_size_ask'],
      dtype='str')

In [27]:
call_filt = ['quote_unixtime', 'quote_readtime', 'quote_date', 'quote_time_hours',
       'underlying_last', 'expire_date', 'expire_unix', 'dte', 'c_delta',
       'c_gamma', 'c_vega', 'c_theta', 'c_rho', 'c_iv', 'c_volume', 'c_last',
       'c_bid', 'c_ask', 'strike', 'strike_distance', 'strike_distance_pct', 'c_size_bid', 'c_size_ask']

In [28]:
call = df[call_filt]
call.columns = call.columns.str.removeprefix('c_')
call['type'] = 'call'

In [29]:
put_filt = ['quote_unixtime', 'quote_readtime', 'quote_date', 'quote_time_hours',
       'underlying_last', 'expire_date', 'expire_unix', 'dte', 'p_delta',
       'p_gamma', 'p_vega', 'p_theta', 'p_rho', 'p_iv', 'p_volume', 'p_last',
       'p_bid', 'p_ask', 'strike', 'strike_distance', 'strike_distance_pct', 'p_size_bid', 'p_size_ask']

In [30]:
put = df[put_filt]
put.columns = put.columns.str.removeprefix('p_')
put['type'] = 'put'

In [31]:
call.shape

(3549809, 24)

In [32]:
put.shape

(3549809, 24)

In [33]:
long_df = pd.concat([call, put], ignore_index = True)
long_df.index.is_unique

True

In [34]:
long_df

,quote_unixtime,quote_readtime,quote_date,quote_time_hours,underlying_last,expire_date,expire_unix,dte,delta,gamma,...,volume,last,bid,ask,strike,strike_distance,strike_distance_pct,size_bid,size_ask,type
0,1630526400,2021-09-01 16:00:00,2021-09-01,16.0,451.85,2021-09-01,1630526400,0.0,1.00000,0.0,...,1.0,182.65,181.09,182.31,270.0,181.9,0.402,1,1,call
1,1630526400,2021-09-01 16:00:00,2021-09-01,16.0,451.85,2021-09-01,1630526400,0.0,1.00000,0.0,...,NaN,0.00,176.09,177.31,275.0,176.9,0.391,1,1,call
2,1630526400,2021-09-01 16:00:00,2021-09-01,16.0,451.85,2021-09-01,1630526400,0.0,1.00000,0.0,...,25.0,157.75,171.09,172.31,280.0,171.9,0.380,1,1,call
3,1630526400,2021-09-01 16:00:00,2021-09-01,16.0,451.85,2021-09-01,1630526400,0.0,1.00000,0.0,...,25.0,153.45,166.14,167.30,285.0,166.9,0.369,1,1,call
4,1630526400,2021-09-01 16:00:00,2021-09-01,16.0,451.85,2021-09-01,1630526400,0.0,1.00000,0.0,...,25.0,147.76,161.09,162.31,290.0,161.9,0.358,1,1,call
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7099613,1614373200,2021-02-26 16:00:00,2021-02-26,16.0,380.36,2023-12-15,1702674000,1022.0,-0.97430,0.0,...,NaN,0.00,196.20,200.50,570.0,189.6,0.499,50,2,put
7099614,1614373200,2021-02-26 16:00:00,2021-02-26,16.0,380.36,2023-12-15,1702674000,1022.0,-0.97337,0.0,...,NaN,0.00,200.92,205.50,575.0,194.6,0.512,200,1,put
7099615,1614373200,2021-02-26 16:00:00,2021-02-26,16.0,380.36,2023-12-15,1702674000,1022.0,-0.97362,0.0,...,NaN,0.00,205.00,210.00,580.0,199.6,0.525,2,1,put
7099616,1614373200,2021-02-26 16:00:00,2021-02-26,16.0,380.36,2023-12-15,1702674000,1022.0,-0.97339,0.0,...,NaN,0.00,209.50,214.50,585.0,204.6,0.538,2,2,put
7099617,1614373200,2021-02-26 16:00:00,2021-02-26,16.0,380.36,2023-12-15,1702674000,1022.0,-0.97411,0.0,...,1.0,211.50,214.00,219.50,590.0,209.6,0.551,2,2,put

In [35]:
print(long_df.shape)
print(long_df['type'].value_counts())

(7099618, 24)
type
call    3549809
put     3549809
Name: count, dtype: int64

In [36]:
long_df.columns

Index(['quote_unixtime', 'quote_readtime', 'quote_date', 'quote_time_hours',
       'underlying_last', 'expire_date', 'expire_unix', 'dte', 'delta',
       'gamma', 'vega', 'theta', 'rho', 'iv', 'volume', 'last', 'bid', 'ask',
       'strike', 'strike_distance', 'strike_distance_pct', 'size_bid',
       'size_ask', 'type'],
      dtype='str')

In [37]:
df.to_parquet(r'../data\processed\raw.parquet')
long_df.to_parquet(r'../data\processed\options_long.parquet')