In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('../data/raw/spy_2020_2022.csv', low_memory= False)

In [3]:
df

,[QUOTE_UNIXTIME],[QUOTE_READTIME],[QUOTE_DATE],[QUOTE_TIME_HOURS],[UNDERLYING_LAST],[EXPIRE_DATE],[EXPIRE_UNIX],[DTE],[C_DELTA],[C_GAMMA],...,[P_LAST],[P_DELTA],[P_GAMMA],[P_VEGA],[P_THETA],[P_RHO],[P_IV],[P_VOLUME],[STRIKE_DISTANCE],[STRIKE_DISTANCE_PCT]
0,1630526400,2021-09-01 16:00,2021-09-01,16.0,451.85,2021-09-01,1630526400,0.0,1.000000,0.000000,...,0.010000,-0.000240,0.000000,0.000040,-0.005090,0.000000,3.412490,3.000000,181.9,0.402
1,1630526400,2021-09-01 16:00,2021-09-01,16.0,451.85,2021-09-01,1630526400,0.0,1.000000,0.000000,...,0.010000,-0.000630,0.000030,0.000190,-0.004800,0.000000,3.297370,0.000000,176.9,0.391
2,1630526400,2021-09-01 16:00,2021-09-01,16.0,451.85,2021-09-01,1630526400,0.0,1.000000,0.000000,...,0.010000,0.000000,0.000000,-0.000230,-0.005340,0.000000,3.183300,11.000000,171.9,0.380
3,1630526400,2021-09-01 16:00,2021-09-01,16.0,451.85,2021-09-01,1630526400,0.0,1.000000,0.000000,...,0.010000,-0.000160,0.000040,0.000380,-0.005320,0.000000,3.072170,50.000000,166.9,0.369
4,1630526400,2021-09-01 16:00,2021-09-01,16.0,451.85,2021-09-01,1630526400,0.0,1.000000,0.000000,...,0.010000,-0.000680,0.000000,0.000450,-0.005150,0.000000,2.962300,0.000000,161.9,0.358
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3589074,1614373200,2021-02-26 16:00,2021-02-26,16.0,380.36,2023-12-15,1702674000,1022.0,0.108570,0.001560,...,0.000000,-0.974300,0.000000,0.000000,-0.009830,-15.938490,0.000340,,189.6,0.499
3589075,1614373200,2021-02-26 16:00,2021-02-26,16.0,380.36,2023-12-15,1702674000,1022.0,0.100860,0.001540,...,0.000000,-0.973370,0.000000,0.000000,-0.009730,-16.078100,0.000000,,194.6,0.512
3589076,1614373200,2021-02-26 16:00,2021-02-26,16.0,380.36,2023-12-15,1702674000,1022.0,0.100310,0.001470,...,0.000000,-0.973620,0.000000,0.000000,-0.009880,-16.217570,0.000410,,199.6,0.525
3589077,1614373200,2021-02-26 16:00,2021-02-26,16.0,380.36,2023-12-15,1702674000,1022.0,0.090500,0.001380,...,0.000000,-0.973390,0.000000,0.000000,-0.009300,-16.357500,-0.000370,,204.6,0.538
3589078,1614373200,2021-02-26 16:00,2021-02-26,16.0,380.36,2023-12-15,1702674000,1022.0,0.090460,0.001350,...,211.500000,-0.974110,0.000000,0.000000,-0.009250,-16.497210,-0.000170,1.000000,209.6,0.551

In [4]:
df.sample(5).T

,2114027,3103663,169668,1447066,2030123
[QUOTE_UNIXTIME],1642194000,1633550400,1629230400,1592856000,1584734400
[QUOTE_READTIME],2022-01-14 16:00,2021-10-06 16:00,2021-08-17 16:00,2020-06-22 16:00,2020-03-20 16:00
[QUOTE_DATE],2022-01-14,2021-10-06,2021-08-17,2020-06-22,2020-03-20
[QUOTE_TIME_HOURS],16.0,16.0,16.0,16.0,16.0
[UNDERLYING_LAST],464.66,434.9,443.95,310.67,228.95
[EXPIRE_DATE],2022-01-21,2022-01-21,2021-09-24,2020-12-31,2020-10-16
[EXPIRE_UNIX],1642798800,1642798800,1632513600,1609448400,1602878400
[DTE],7.0,107.04,38.0,192.04,210.0
[C_DELTA],0.832670,0.070820,0.940210,0.665840,0.019110
[C_GAMMA],0.020160,0.004430,0.001540,0.005200,0.001050
[C_VEGA],0.169420,0.321490,0.147930,0.815600,0.083240
[C_THETA],-0.203420,-0.018690,-0.066840,-0.062170,-0.004910
[C_RHO],0.079040,0.088490,0.096650,0.783200,0.023990
[C_IV],0.184140,0.127580,0.419370,0.309990,0.266230
[C_VOLUME],20.000000,2.000000,,1.000000,1.000000
[C_LAST],12.440000,0.900000,0.000000,39.400000,2.140000
[C_SIZE],70 x 50,211 x 105,104 x 104,1 x 1,1 x 625
[C_BID],12.690000,0.910000,82.930000,37.960000,0.160000
[C_ASK],12.910000,0.930000,83.970000,39.740000,0.470000
[STRIKE],453.0,482.0,361.0,288.0,353.0
[P_BID],1.070000,48.300000,0.580000,17.540000,123.760000
[P_ASK],1.100000,50.180000,0.590000,18.150000,126.890000
[P_SIZE],83 x 130,84 x 36,125 x 1756,1 x 1,1 x 100
[P_LAST],1.070000,0.000000,0.530000,19.800000,0.000000
[P_DELTA],-0.164040,-0.906790,-0.029580,-0.333270,-0.990930
[P_GAMMA],0.020200,0.004950,0.001380,0.005100,0.000330
[P_VEGA],0.167660,0.390020,0.096860,0.818650,0.018860
[P_THETA],-0.196720,-0.031330,-0.043400,-0.068610,-0.006870
[P_RHO],-0.016220,-1.308610,-0.014980,-0.641050,-2.034440
[P_IV],0.181460,0.140300,0.340570,0.315340,0.209080
[P_VOLUME],2297.000000,,1.000000,2.000000,
[STRIKE_DISTANCE],11.7,47.1,82.9,22.7,124.1
[STRIKE_DISTANCE_PCT],0.025,0.108,0.187,0.073,0.542